// Copyright (c) 2020, 2022, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

// Code generated by lister-gen. DO NOT EDIT.

package v1

// VerrazzanoMonitoringInstanceListerExpansion allows custom methods to be added to
// VerrazzanoMonitoringInstanceLister.
type VerrazzanoMonitoringInstanceListerExpansion interface{}

// VerrazzanoMonitoringInstanceNamespaceListerExpansion allows custom methods to be added to
// VerrazzanoMonitoringInstanceNamespaceLister.
type VerrazzanoMonitoringInstanceNamespaceListerExpansion interface{}
