# Copyright (c) 2023, Oracle Corporation and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.

# ---------------------------------------------------------------------------
# Verrazzano GitHub Actions VMO Build.
# ---------------------------------------------------------------------------

name: VMO Build
run-name: GitHub Actions workflow to build the Verrazzano Monitoring Operator 🚀

on:
  push:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      # Checkout VMO repo
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      # Login against a Docker registry
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Get VMO image name for developer branches
      - name: Get image name (developer)
        if: ${{ !github.ref_protected }}
        run: echo "IMAGE_NAME=${{ github.repository }}-temp" >> "$GITHUB_ENV"

      # Get VMO image tag
      - name: Get image tag
        run: |
          DEV_VERSION=$(grep verrazzano-development-version .verrazzano-development-version | cut -d= -f 2)
          TIME_STAMP=$(date +'%Y%m%d%H%M%S')
          SHORT_COMMIT_SHA=$(git rev-parse --short HEAD)
          echo "DOCKER_IMAGE_TAG=v$DEV_VERSION-$TIME_STAMP-$SHORT_COMMIT_SHA" >> "$GITHUB_ENV"
